i18n/de.yaml

As discussed in  [hugo-theme-hinode-child#40](https://github.com/markdumay/hugo-theme-hinode-child/issues/40), i18n translation for German.

Add German translation

---

assets/scss/components/_syntax-dark.scss
assets/scss/components/_syntax.scss
package.json

Fix line highlights

---

layouts/partials/footer/social.html
package-lock.json
package.json

Suppress social footer when no media are defined

---

layouts/_default/list.html
layouts/_default/single.html
layouts/partials/utilities/ProcessContent.html

Fix emoji support

---

exampleSite/content/fr/blog/components.md

Update French Translation with latest hinode version

---

i18n/zh-hans.yaml
i18n/zh-hant.yaml

Ah, I understand now. It was just a minor issue with the file naming earlier. However, I'll still go ahead and submit the translated file. It will be more convenient for future Chinese users as well.
resolved #663

Add Chinese translation files

---

assets/js/analytics.js

Fix Google Analytics config

---

go.mod
go.sum
layouts/partials/utilities/git.html

Fix missing translation of git footer

---

config/_default/hugo.toml
data/structures/scripts.yml
go.mod
go.sum
layouts/partials/footer/optional-scripts.html
layouts/partials/footer/scripts.html
layouts/partials/utilities/InitModules.html
package-lock.json
package.json

Support localization of script bundles

---

data/structures/youtube.yml
exampleSite/content/en/blog/bootstrap-elements.md
layouts/shortcodes/youtube.html

Includes the following changes:
- Adds support to retrieve the YouTube title from the video metadata
- Adjusts autoplay configuration
- Improves argument handling

Refactor YouTube shortcode

---

assets/js/critical/color.js
assets/scss/common/_styles.scss
assets/scss/components/_navbar.scss
layouts/_default/baseof.html
package-lock.json
package.json

Reduce screen flickering when using color mode

---

assets/js/critical/color.js
assets/scss/components/_navbar.scss
exampleSite/hugo_stats.json
hugo_stats.json

Fix rendering of theme toggle button

---

data/structures/link.yml
exampleSite/content/en/about.md
exampleSite/content/en/blog/bootstrap-elements.md
exampleSite/content/en/blog/components.md
exampleSite/content/fr/about.md
exampleSite/content/fr/blog/bootstrap-elements.md
exampleSite/content/fr/blog/components.md
exampleSite/content/nl/about.md
exampleSite/hugo_stats.json
layouts/_default/_markup/render-link.html
layouts/partials/assets/link.html
package-lock.json
package.json

Support markdown links

---

layouts/partials/assets/link.html
layouts/shortcodes/link.html

Support links to static files and page resources

---

layouts/_default/_markup/render-blockquote.html

Improve handling of unsupported alert types

---

assets/js/navbar.js

Fixes Switching themes does not work properly #1177

Fix navbar color mode update

---

assets/js/sharing.js
layouts/partials/assets/sharing.html

Handles pages that render multiple sharing buttons to cater for responsive layout.

Support multiple sharing buttons on same page

---

assets/js/critical/languageSelector.js
exampleSite/hugo_stats.json
go.mod
go.sum
layouts/partials/assets/link.html

Improve deployment to subfolder

---

layouts/partials/single/thumbnail.html

Add params ratio for thumbnails
[thumbnails]
ratio = "16x9"

Params config for thumbnails.ratio

---

layouts/partials/assets/breadcrumb.html
package-lock.json
package.json

Ignores list pages that are not built

Suppress empty breadcrumb sections

---

config/_default/params.toml
exampleSite/config/_default/params.toml
layouts/partials/assets/card-group.html
layouts/partials/assets/link.html
package-lock.json
package.json

Use Params.main.internalLinks.pretty = true

Add option to forcefully include trailing slash in links and card group buttons

---

config/postcss.config.js
exampleSite/config/postcss.config.js
package-lock.json
package.json

Upgrade to PurgeCSS v7

---

i18n/pt-br.yaml

Hi there,
I have added the translation for Brazilian Portuguese `pt-br`. In this PR, I am only submitting the `pt-br.yaml` file. Let me know if you want me to translate the rest, such as the menu entries and `languages.toml`, for example.
Best regards.

Add Brazilian Portuguese translations
